const UserDetails = [
  {
    name: "Rajesh Sharma",
    role: "Frontend Developer",
    email: "rajesh.sharma@example.com",
    phone: "9876543210",
    course: "React Basic",
    status: "Unplaced",
  },
  {
    name: "Priya Singh",
    role: "UI/UX Designer",
    email: "priya.singh@example.com",
    phone: "8765432109",
    course: "UI/UX Designer",
    status: "Placed",
  },
  {
    name: "Amit Verma",
    role: "DevOps Engineer",
    email: "amit.verma@example.com",
    phone: "7654321098",
    course: "JavaScript Fundamentals",
    status: "Unplaced",
  },
  {
    name: "Anjali Patel",
    role: "Data Scientist",
    email: "anjali.patel@example.com",
    phone: "6543210987",
    course: "Advance CSS",
    status: "Placed",
  },
  {
    name: "Vikram Desai",
    role: "Backend Developer",
    email: "vikram.desai@example.com",
    phone: "5432109876",
    course: "Backend Development",
    status: "Placed",
  },
  {
    name: "Meera Nair",
    role: "AI Engineer",
    email: "meera.nair@example.com",
    phone: "4321098765",
    course: "React Basic",
    status: "Unplaced",
  },
  {
    name: "Rohan Gupta",
    role: "Cybersecurity Analyst",
    email: "rohan.gupta@example.com",
    phone: "3210987654",
    course: "JavaScript Fundamentals",
    status: "Placed",
  },
  {
    name: "Sneha Iyer",
    role: "Database Administrator",
    email: "sneha.iyer@example.com",
    phone: "2109876543",
    course: "UI/UX Designer",
    status: "Unplaced",
  },
];

export default UserDetails;
